[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 1

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytecode = true
fail_on_revert = false

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
dictionary_weight = 80
include_storage = true
include_push_bytecode = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[profile.lite]
fuzz = { runs = 10 }
invariant = { runs = 10 }
