name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-web:
    name: Deploy Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm build --filter web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web

  deploy-contracts:
    name: Deploy Contracts
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Deploy to Amoy
        run: |
          cd contracts
          forge script script/Deploy.s.sol \
            --rpc-url ${{ secrets.AMOY_RPC_URL }} \
            --private-key ${{ secrets.PRIVATE_KEY }} \
            --broadcast \
            --verify
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - name: Deploy to Polygon
        run: |
          cd contracts
          forge script script/Deploy.s.sol \
            --rpc-url ${{ secrets.POLYGON_RPC_URL }} \
            --private-key ${{ secrets.PRIVATE_KEY }} \
            --broadcast \
            --verify
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
